S07_Activity/S07_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

S07_Activity/django_practice/urls.py
from django.urls import path, re_path
from . import views

app_name = 'django_practice'
urlpatterns = [
	path('', views.index,name= 'index'),
	path('register',views.register, name='register'),
	path('change_password',views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_item', views.add_item, name="add_item"),
	path('add_event', views.add_event, name="add_event"),
	path('update_profile', views.update_profile, name="update_profile"),
	path('grocery<int:groceryitem_id>/', views.groceryitem, name = 'viewgroceryitem'),
	path('grocery<int:groceryitem_id>/edit', views.update_item, name='update_item'),
	path('grocery<int:groceryitem_id>/delete', views.delete_item, name='delete_item'),
	path('event<int:eventitem_id>', views.eventitem, name = 'vieweventitem'),
	path('event<int:eventitem_id>/edit', views.update_event, name='update_event'),
	path('event<int:eventitem_id>/delete', views.delete_event, name='delete_event'),


	
]

S07_Activity/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}Grocery Item and Event App{% endblock %} </title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	{% include "navbar.html" %}
	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

S07_Activity/templates/base1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}Grocery Item and Event App{% endblock %} </title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

S07_Activity/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand" href="{% url 'django_practice:index' %}"><b>CRUD APP</b></span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse offset-lg-7" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'django_practice:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'django_practice:add_item' %}">Add Grocery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'django_practice:add_event' %}">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'django_practice:update_profile' %}">Update Profile</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'django_practice:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
        </li>
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>