S07_Activity/S07_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

S07_Activity/django_practice/urls.py
from django.urls import path, re_path
from . import views

app_name = 'django_practice'
urlpatterns = [
	path('', views.index,name= 'index'),
	path('register',views.register, name='register'),
	path('change_password',views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_item', views.add_item, name="add_item"),
	path('add_event', views.add_event, name="add_event"),
	path('update_profile', views.update_profile, name="update_profile"),
	path('grocery<int:groceryitem_id>/', views.groceryitem, name = 'viewgroceryitem'),
	path('grocery<int:groceryitem_id>/edit', views.update_item, name='update_item'),
	path('grocery<int:groceryitem_id>/delete', views.delete_item, name='delete_item'),
	path('event<int:eventitem_id>', views.eventitem, name = 'vieweventitem'),
	path('event<int:eventitem_id>/edit', views.update_event, name='update_event'),
	path('event<int:eventitem_id>/delete', views.delete_event, name='delete_event'),


	
]

S07_Activity/django_practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class GroceryItem(models.Model):
	item_name =  models.CharField(max_length=50)
	category = models.CharField(max_length=50)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete = models.CASCADE, default ="")

class EventItem(models.Model):
	event_name =  models.CharField(max_length=50)
	description = models.CharField(max_length=50)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete = models.CASCADE, default ="")
	date_input = models.DateTimeField('date input')

S07_Activity/django_practice/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	date_input = forms.DateTimeField()

class UpdateItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class UpdateProfileForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

S07_Activity/django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
from django.forms.models import model_to_dict
from django.utils import timezone
# Create your views here.

from .models import GroceryItem,EventItem
from .forms import LoginForm, AddItemForm, UpdateItemForm, RegisterForm
from .forms import AddEventForm, UpdateEventForm, UpdateProfileForm


def index(request):
	groceryitem_list = GroceryItem.objects.filter(user_id = request.user.id)
	eventitem_list = EventItem.objects.filter(user_id = request.user.id)
	context = {
		'groceryitem_list': groceryitem_list,
		'eventitem_list' : eventitem_list,
		'user': request.user
	}
	return render(request, "django_practice/index.html",context)

def groceryitem(request,groceryitem_id):
	groceryitem = get_object_or_404(GroceryItem,pk=groceryitem_id)

	return render (request, "django_practice/groceryitem.html", model_to_dict(groceryitem))

def eventitem(request,eventitem_id):
	eventitem = get_object_or_404(EventItem,pk=eventitem_id)

	return render (request, "django_practice/eventitem.html", model_to_dict(eventitem))



def register(request):
	
	context = {}
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid() == False:
			form = RegisterForm()
		else:
			user = User()
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			is_staff = False
			is_active = True 

			duplicates = User.objects.filter(username = username)

			if not duplicates:
				
				User.objects.create(username = username, first_name = first_name, last_name = last_name, email = email, is_staff = is_staff , is_active = is_active , password = password)

				authenticated_user = User.objects.get(username = username)
				authenticated_user.set_password(password)
				authenticated_user.save()

		
				return redirect("django_practice:login")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/register.html", context)


def change_password(request):


	user = authenticate(username="alexbuena", password="alexa1")
	print(user)

	if user is None:
		authenticated_user = User.objects.get(username="johndoe")
		authenticated_user.set_password('johndoe1')
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		'user':request.user
	}

	return render(request, "django_practice/change_password.html", context)

def login_view(request):
	context = {}
	
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid() == False:
			form = LoginForm()
		else:

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			
			user = authenticate(username=username, password=password)
			print(user)
				
			context = {
				"username": username,
				"password": password
			}
	
			if user is not None:
				login(request,user)
				return redirect("django_practice:index")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("django_practice:login")

def update_profile(request):

	usern = User.objects.filter(id = request.user.id)
	context ={
		# "user" : user.request,
		"username" : usern[0].username,
		"first_name": usern[0].first_name,
		"last_name": usern[0].last_name,
		"password": usern[0].password,
		"email": usern[0].email
	}

	if request.method == 'POST':
		form = UpdateProfileForm(request.POST)
		if form.is_valid() == False:
			form = UpdateProfileForm()
		else:
			
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']

			if usern:
				usern[0].username = username
				usern[0].first_name = first_name
				usern[0].last_name = last_name
				usern[0].email = email
				# usern[0].password = password
				usern[0].set_password(password)
				usern[0].save()

				return redirect("django_practice:index")
			else:
				context ={
					"error": True
				}
	return render(request, "django_practice/update_profile.html", context)

def add_item(request):
	context = {}
	if request.method == 'POST':
		form = AddItemForm(request.POST)
		if form.is_valid() == False:
			form = AddItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']

			duplicates = GroceryItem.objects.filter(item_name = item_name)

			if not duplicates:
				GroceryItem.objects.create(item_name = item_name, category = category, date_created = timezone.now(),user_id=request.user.id)
				return redirect("django_practice:index")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/add_item.html", context)

def add_event(request):
	context = {}
	if request.method == 'POST':
		form = AddEventForm(request.POST)
		if form.is_valid() == False:
			form = AddEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			date_input = form.cleaned_data['date_input']

			duplicates = EventItem.objects.filter(event_name = event_name)

			if not duplicates:
				EventItem.objects.create(event_name = event_name, description = description, date_created = timezone.now(), date_input = date_input,user_id=request.user.id)
				return redirect("django_practice:index")
			else:
				context = {
					"error": True
				}
	return render(request, "django_practice/add_event.html", context)

def update_item(request, groceryitem_id):
	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id)

	context ={
		"user": request.user,
		"groceryitem_id": groceryitem_id,
		"item_name": groceryitem[0].item_name,
		"category": groceryitem[0].category,
		"status": groceryitem[0].status
	}
	if request.method == 'POST':
		form = UpdateItemForm(request.POST)
		if form.is_valid() == False:
			form = UpdateItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']
			status = form.cleaned_data['status']

			if groceryitem:
				groceryitem[0].item_name = item_name
				groceryitem[0].category = category
				groceryitem[0].status = status

				groceryitem[0].save()
				return redirect("django_practice:index")

			else:
				context ={
					"error": True
				}
	return render(request, "django_practice/update_item.html", context)

def update_event(request, eventitem_id):
	eventitem = EventItem.objects.filter(pk=eventitem_id)

	context ={
		"user": request.user,
		"eventitem_id": eventitem_id,
		"event_name": eventitem[0].event_name,
		"description": eventitem[0].description,
		"status": eventitem[0].status,
		"date_input" : eventitem[0].date_input
	}

	if request.method == 'POST':
		form = UpdateEventForm(request.POST)
		if form.is_valid() == False:
			form = UpdateEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']
			# date_input = form.cleaned_data['date_input']

			if eventitem:
				eventitem[0].event_name = event_name
				eventitem[0].description = description
				eventitem[0].status = status
				# eventitem[0].date_input = date_input

				eventitem[0].save()
				return redirect("django_practice:index")

			else:
				context ={
					"error": True
				}
	return render(request, "django_practice/update_event.html", context)

def delete_item(request, groceryitem_id):
	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id).delete()
	return redirect("django_practice:index")

def delete_event(request, eventitem_id):
	eventitem = EventItem.objects.filter(pk=eventitem_id).delete()
	return redirect("django_practice:index")

S07_Activity/django_practice/templates/django_practice/add_event.html
{% extends 'base.html' %}
{% block title %}Add Event{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add an Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}
				<form action="{% url 'django_practice:add_event' %}" method="post">
				{% csrf_token %}

					<div class="mb-3">
						<label for="event_name">Event Name:</label>
						<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description:</label>
						<textarea class="form-control" name="description" value="{{ description }}"required></textarea>
					</div>

					<div class="mb-3">
						<label for="date_input">Date:</label>
						<input class="form-control" id="date_input" type="date"name="date_input" value="{{ date_input }}"required></input>
					</div>


					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Add Event">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

S07_Activity/django_practice/templates/django_practice/add_item.html
{% extends 'base.html' %}
{% block title %}Add Item{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add an Item</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate item found</p>
				{% endif %}
				<form action="{% url 'django_practice:add_item' %}" method="post">
				{% csrf_token %}

					<div class="mb-3">
						<label for="item_name">Item Name:</label>
						<input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="category">Category:</label>
						<textarea class="form-control" name="category" value="{{ category }}"required></textarea>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Add Item">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

S07_Activity/django_practice/templates/django_practice/change_password.html
{% extends 'base1.html' %}
{% block title %}Home{% endblock %}
{% block content %}
	<h1 class="text-center my-3">Verifying Account for {{ user.first_name }} {{ user.last_name }}!</h1>


{% endblock %}

S07_Activity/django_practice/templates/django_practice/eventitem.html
{% extends 'base.html' %}
{% block title %}Event Item{% endblock %}
{% block content %}

<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Scheduled Date</h3>
	<p>{{ date_input }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:update_event' id %}" class="text-light text-decoration-none">Edit Event</a>
	</button>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:delete_event' id %}" class="text-light text-decoration-none">Delete Event</a>
	</button>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:index' %}" class="text-light text-decoration-none">Back to Event List</a>
	</button>
</div>


{% endblock %}

S07_Activity/django_practice/templates/django_practice/groceryitem.html
{% extends 'base.html' %}
{% block title %}Grocery Item{% endblock %}
{% block content %}

<div class="text-center my-3">
	<h1>{{ item_name }}</h1>
	<div class="list-group-item col-lg-6 offset-lg-3  ">
		<h3>Category</h3>
		<p>{{ category }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>

		<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:update_item' id %}" class="text-light text-decoration-none">Edit Item</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:delete_item' id %}" class="text-light text-decoration-none">Delete Item</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none"><a href ="{% url 'django_practice:index' %}" class="text-light text-decoration-none">Back to Grocery List</a>
		</button>
	</div>
</div>


{% endblock %}

S07_Activity/django_practice/templates/django_practice/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
	{% if groceryitem_list or eventitem_list and user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
		<div class="container">
			<div class="row">
				<div class="list-group-item col-lg-7 offset-lg-3  ">
					<h3 class="text-center mb-3">My Grocery Item</h3>
					<ul class="list-group col-lg-3 offset-lg-5 text-start">
					{% for groceryitem in groceryitem_list %}
						<li class="list-group-item">
							<a href="{% url 'django_practice:viewgroceryitem' groceryitem.id %}" class="text-decoration-none">   {{ forloop.counter }} {{groceryitem.item_name}}</a>
						</li>
						<br>
					{% endfor %}
					</ul>
				</div>
				<div class="list-group-item col-lg-7 offset-lg-3 ">
					<h3 class="text-center mb-3">My Events</h3>
					<ul class="list-group col-lg-3 offset-lg-5 text-start">
					{% for eventitem in eventitem_list %}
						<li class="list-group-item">
							<a href="{% url 'django_practice:vieweventitem' eventitem.id %}" class="text-decoration-none">   {{ forloop.counter }} {{eventitem.event_name}}</a>
						</li>
						<br>
					{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page </h1>
		<p class= "text-center">Kindly Login<a href="{% url 'django_practice:login' %}"> here</a></p>
	{% else %}
		<h1 class="text-center"> No items have been created</h1>
		
	{% endif %}
{% endblock %}

S07_Activity/django_practice/templates/django_practice/login.html
{% extends 'base1.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}	
			<form action="{% url 'django_practice:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
			<br><br>
			<div class="text-end">
					<h5 class= "text-end">Don't have an account? <a class="btn btn-outline-dark" href="{% url 'django_practice:register' %}">Register here</a></h5>
					
			</div>

		</div>
	</div>
</div>
{% endblock %}

S07_Activity/django_practice/templates/django_practice/register.html
{% extends 'base1.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
				<p class="text-danger">User Already Registered</p>
			{% endif %}	
			<form action="{% url 'django_practice:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="first_name">First Name:</label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="last_name">Last Name:</label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="email">Email:</label>
					<input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="30" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div>

				<!-- <div class="mb-3">
					<label for="password">Confirm Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div> -->

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>

			</form>
			<br><br>
			<div class="text-end">
					<h5 class= "text-end">Already have an account? <a class="btn btn-outline-dark" href="{% url 'django_practice:login' %}">Login here</a></h5>
					
		</div>
	</div>
</div>
{% endblock %}

S07_Activity/django_practice/templates/django_practice/update_event.html
{% extends 'base.html' %}
{% block title %}Update Event{% endblock %}
{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Event</h1>
				{% if error == True %}
					<p class="text-danger">Event not found</p>
				{% endif %}	
				<form action="{% url 'django_practice:update_event' eventitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="event_name">Event Name:</label>
						<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description:</label>
						<textarea class="form-control" name="description" value="{{ description }}"required></textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status:</label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>
					<!-- <div class="mb-3">
						<label for="date_input">Date:</label>
						<input class="form-control" id="date_input" type="date"name="date_input" value="{{ date_input }}"required></input>
					</div> -->

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Event">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to enter this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'django_practice:login' %}"> here</p>
	{% endif %}
{% endblock %}

S07_Activity/django_practice/templates/django_practice/update_item.html
{% extends 'base.html' %}
{% block title %}Update Item{% endblock %}
{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Item</h1>
				{% if error == True %}
					<p class="text-danger">Item not found</p>
				{% endif %}	
				<form action="{% url 'django_practice:update_item' groceryitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="item_name">Item Name:</label>
						<input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="category">Category:</label>
						<textarea class="form-control" name="category" value="{{ category }}"required></textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status:</label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Item">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to enter this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'django_practice:login' %}"> here</p>
	{% endif %}
{% endblock %}

S07_Activity/django_practice/templates/django_practice/update_profile.html
{% extends 'base.html' %}
{% block title %}Update Account{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Update Account</h1>

			<form action="{% url 'django_practice:update_profile' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="first_name">First Name:</label>
					<input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="last_name">Last Name:</label>
					<input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="email">Email:</label>
					<input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="30" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div>

				<!-- <div class="mb-3">
					<label for="password">Confirm Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="30" required>
				</div> -->

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update">
				</div>

			</form>
			<br><br>
		
	</div>
</div>
{% endblock %}